[package]
name            = "mongors"
version         = "0.1.0"
license         = "MIT"
authors         = ["mitum <dangcheng@hotmail.com>"]
description     = "Rust driver for MongoDB"
keywords        = ["mongo", "mongodb", "mongodb_driver", "database", "nosql"]
documentation   = "https://docs.rs/mongors"
homepage        = "https://github.com/mitum/mongo-rust-driver"
repository      = "https://github.com/mitum/mongo-rust-driver"
readme          = "README.md"

[dependencies]
